// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: pkg/api/jobworker.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_jobInit          JobStatus = 0
	JobStatus_jobScheduled     JobStatus = 1
	JobStatus_jobFailedToStart JobStatus = 2
	JobStatus_jobRunning       JobStatus = 3
	JobStatus_jobStopped       JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "jobInit",
		1: "jobScheduled",
		2: "jobFailedToStart",
		3: "jobRunning",
		4: "jobStopped",
	}
	JobStatus_value = map[string]int32{
		"jobInit":          0,
		"jobScheduled":     1,
		"jobFailedToStart": 2,
		"jobRunning":       3,
		"jobStopped":       4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_jobworker_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_pkg_api_jobworker_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_jobworker_proto_rawDescGZIP(), []int{0}
}

type StartJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command   string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Arguments []string `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_jobworker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_jobworker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_jobworker_proto_rawDescGZIP(), []int{0}
}

func (x *StartJobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartJobRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type JobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_jobworker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_jobworker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_jobworker_proto_rawDescGZIP(), []int{1}
}

func (x *JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId    string    `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Pid      int32     `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	ExitCode int32     `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Status   JobStatus `protobuf:"varint,4,opt,name=status,proto3,enum=jobworker.JobStatus" json:"status,omitempty"`
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_jobworker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_jobworker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_jobworker_proto_rawDescGZIP(), []int{2}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *JobResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JobResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_jobInit
}

type StreamJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StreamJobResponse) Reset() {
	*x = StreamJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_jobworker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamJobResponse) ProtoMessage() {}

func (x *StreamJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_jobworker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamJobResponse.ProtoReflect.Descriptor instead.
func (*StreamJobResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_jobworker_proto_rawDescGZIP(), []int{3}
}

func (x *StreamJobResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_pkg_api_jobworker_proto protoreflect.FileDescriptor

var file_pkg_api_jobworker_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6a, 0x6f, 0x62, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x22, 0x49, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x23, 0x0a, 0x0a, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a,
	0x6f, 0x62, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x0b, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6a, 0x6f, 0x62,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x60, 0x0a, 0x09, 0x4a, 0x6f, 0x62, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x6a, 0x6f, 0x62, 0x49, 0x6e, 0x69, 0x74, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x6a, 0x6f, 0x62, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x64, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x6a, 0x6f, 0x62, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x54, 0x6f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x6a, 0x6f, 0x62,
	0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x6a, 0x6f, 0x62,
	0x53, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x10, 0x04, 0x32, 0x84, 0x02, 0x0a, 0x09, 0x4a, 0x6f,
	0x62, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x4a, 0x6f, 0x62, 0x12, 0x1a, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x4a,
	0x6f, 0x62, 0x12, 0x15, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x4a,
	0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6a, 0x6f, 0x62, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x39, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4a, 0x6f, 0x62, 0x12, 0x15, 0x2e,
	0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4a, 0x6f, 0x62, 0x12, 0x15, 0x2e, 0x6a, 0x6f, 0x62, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x42, 0x13, 0x5a, 0x11, 0x6a, 0x6f, 0x62, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_jobworker_proto_rawDescOnce sync.Once
	file_pkg_api_jobworker_proto_rawDescData = file_pkg_api_jobworker_proto_rawDesc
)

func file_pkg_api_jobworker_proto_rawDescGZIP() []byte {
	file_pkg_api_jobworker_proto_rawDescOnce.Do(func() {
		file_pkg_api_jobworker_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_jobworker_proto_rawDescData)
	})
	return file_pkg_api_jobworker_proto_rawDescData
}

var file_pkg_api_jobworker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_jobworker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_jobworker_proto_goTypes = []interface{}{
	(JobStatus)(0),            // 0: jobworker.JobStatus
	(*StartJobRequest)(nil),   // 1: jobworker.StartJobRequest
	(*JobRequest)(nil),        // 2: jobworker.JobRequest
	(*JobResponse)(nil),       // 3: jobworker.JobResponse
	(*StreamJobResponse)(nil), // 4: jobworker.StreamJobResponse
}
var file_pkg_api_jobworker_proto_depIdxs = []int32{
	0, // 0: jobworker.JobResponse.status:type_name -> jobworker.JobStatus
	1, // 1: jobworker.JobWorker.StartJob:input_type -> jobworker.StartJobRequest
	2, // 2: jobworker.JobWorker.StopJob:input_type -> jobworker.JobRequest
	2, // 3: jobworker.JobWorker.QueryJob:input_type -> jobworker.JobRequest
	2, // 4: jobworker.JobWorker.StreamJob:input_type -> jobworker.JobRequest
	3, // 5: jobworker.JobWorker.StartJob:output_type -> jobworker.JobResponse
	3, // 6: jobworker.JobWorker.StopJob:output_type -> jobworker.JobResponse
	3, // 7: jobworker.JobWorker.QueryJob:output_type -> jobworker.JobResponse
	4, // 8: jobworker.JobWorker.StreamJob:output_type -> jobworker.StreamJobResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_jobworker_proto_init() }
func file_pkg_api_jobworker_proto_init() {
	if File_pkg_api_jobworker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_jobworker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_jobworker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_jobworker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_jobworker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_jobworker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_jobworker_proto_goTypes,
		DependencyIndexes: file_pkg_api_jobworker_proto_depIdxs,
		EnumInfos:         file_pkg_api_jobworker_proto_enumTypes,
		MessageInfos:      file_pkg_api_jobworker_proto_msgTypes,
	}.Build()
	File_pkg_api_jobworker_proto = out.File
	file_pkg_api_jobworker_proto_rawDesc = nil
	file_pkg_api_jobworker_proto_goTypes = nil
	file_pkg_api_jobworker_proto_depIdxs = nil
}
